theme: jekyll-theme-hacker
plugins:
  - jekyll-relative-links
site:
  url: https://critical-ai.dev/awesome-safety-critical-ai/
relative_links:
  enabled: true
  collections: true
include:
  - CITATION.cff
  - CONTRIBUTING
  - README.md
  - LICENSE
  - PULL_REQUEST_TEMPLATE.md
