aliveStatusCodes:
  - 200
  - 202
  - 403
  - 406
dirs:
  - .
ignorePatterns:
  # ToC links
  - pattern: "^#[-a-z]*"
  # MLOps community // ERR_NAME_NOT_RESOLVED
  - pattern: "^https://home.mlops.community.*"
  # Images
  - pattern: "^images/.*"