# .github/workflows/check-links.yml

name: Check Markdown links

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    # Check on the first day of each month
    - cron: "0 0 1 * *"

jobs:
  markdown-link-check:
    name: runner / linkspector
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v4
      - name: 🧶 Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          config_file: .github/linters/.linkspector.yml
          fail_on_error: true
          filter_mode: nofilter